addon_start:
  description: Start a Hass.io docker add-on.
  fields:
    addon:
      description: The add-on slug.
      example: core_ssh

addon_restart:
  description: Restart a Hass.io docker add-on.
  fields:
    addon:
      description: The add-on slug.
      example: core_ssh

addon_stdin:
  description: Write data to a Hass.io docker add-on stdin .
  fields:
    addon:
      description: The add-on slug.
      example: core_ssh

addon_stop:
  description: Stop a Hass.io docker add-on.
  fields:
    addon:
      description: The add-on slug.
      example: core_ssh

homeassistant_update:
  description: Update the Home Assistant docker image.
  fields:
    version:
      description: Optional or it will be use the latest version.
      example: 0.40.1

host_reboot:
  description: Reboot the host system.

host_shutdown:
  description: Poweroff the host system.

snapshot_full:
  description: Create a full snapshot.
  fields:
    name:
      description: Optional or it will be the current date and time.
      example: "Snapshot 1"
    password:
      description: Optional password.
      example: "password"

snapshot_partial:
  description: Create a partial snapshot.
  fields:
    addons:
      description: Optional list of addon slugs.
      example: ["core_ssh", "core_samba", "core_mosquitto"]
    folders:
      description: Optional list of directories.
      example: ["homeassistant", "share"]
    name:
      description: Optional or it will be the current date and time.
      example: "Partial Snapshot 1"
    password:
      description: Optional password.
      example: "password"
