addon_start:
  description: Start add-on.
  fields:
    addon:
      name: Add-on
      description: The add-on slug.
      example: core_ssh
      selector:
        addon:

addon_restart:
  description: Restart add-on.
  fields:
    addon:
      name: Add-on
      description: The add-on slug.
      example: core_ssh
      selector:
        addon:

addon_stdin:
  description: Write data to add-on stdin .
  fields:
    addon:
      name: Add-on
      description: The add-on slug.
      example: core_ssh
      selector:
        addon:

addon_stop:
  description: Stop add-on.
  fields:
    addon:
      name: Add-on
      description: The add-on slug.
      example: core_ssh
      selector:
        addon:

host_reboot:
  description: Reboot the host system.

host_shutdown:
  description: Poweroff the host system.

snapshot_full:
  description: Create a full snapshot.
  fields:
    name:
      name: Name
      description: Optional or it will be the current date and time.
      example: "Snapshot 1"
      selector:
        text:
    password:
      name: Password
      description: Optional password.
      example: "password"
      selector:
        text:

snapshot_partial:
  description: Create a partial snapshot.
  fields:
    addons:
      description: Optional list of addon slugs.
      example: ["core_ssh", "core_samba", "core_mosquitto"]
      selector:
        object:
    folders:
      name: Folders
      description: Optional list of directories.
      example: ["homeassistant", "share"]
      selector:
        object:
    name:
      name: Name
      description: Optional or it will be the current date and time.
      example: "Partial Snapshot 1"
      selector:
        text:
    password:
      name: Password
      description: Optional password.
      example: "password"
      selector:
        text:
